### ISSUE TITLE
Unique Sample IDs error

### ISSUE THREAD

**Issue by cwanderdx** [CCY-dev/LongDat#1]
Hi, thanks for the great tool. I've almost completed a successful test with my own dataset, but the "master_created" step is throwing me an error no matter how I format my sample IDs, interestingly only from the metadata table.

The specific error script I get reads:

"Error in make_master_table(metadata_table = metadata, feature_table = feature,  : 
Error! There are repeated sample_IDs in the metadata_table.
Please make sure that the sample_IDs are unique for each sample."

Where metadata and feature are the manually loaded tables each containing unique sample IDs numbered 1-99, with no duplications.  I have also tried this using characters + numbers as sample labels, arriving at the same error. 

This ultimately blocks me from running a proper covariate test, so I'm missing that portion of the analysis.  As a temporary workaround to get longitudinal change, I can simply use my old master table, but again, that omits the covariate analysis.  Any help is appreciated, thanks!

**Comment by CCY-dev** [comment]
Hi, I'm glad that you find the tool useful. Below is the code where your error occurs in make_master_table()

if (length(unique(metadata_table[ , sample_ID])) != nrow(metadata_table)) {
    stop("Error! There are repeated sample_IDs in the metadata_table.
    Please make sure that sample_IDs are unique for each sample.")}

Here, it examines if the number of unique sample_ID is the same as the row number of the metadata table. So it checks if each row has its unique sample ID, which is important because the sample ID is used to merge the metadata and feature table. I guess you have already checked this. Below are some points to pay attention to when using the make_master_table():

1. The row numbers of metadata and feature tables should be the same.
2. Sample_IDs are unique for each sample (i.e. no repeated sample_ID)
3. Metadata and feature tables have the same sample_IDs. If sample_IDs don’t match between the two tables, the joining process will fail.
4. As mentioned above, the feature table should include only the columns of sample_ID and features.
5. Avoid using characters that don’t belong to ASCII printable for the column names.

If you still can't solve the problem, I'd be happy to examine your metadata and feature tables. You can send an example of your data with the important information changed or anonymized (but keep the sample ID name as it is so I can see what the problem is) to Chia-Yu.Chen@mdc-berlin.de.

**Comment by toobiwankenobi** [comment]
I had the same issue and I checked your source code. The implement checks don't work if the input object is a `tibble data.frame`. Maybe you can adjust the source code to handle both `data.frame` and tibble `data.frame` objects.

**Comment by CCY-dev** [comment]
Hi! That's a great point! I've revised the package, updated it to version 1.1.3, and submitted it to CRAN. It should be publicly available in a few days. This update includes a modification to the make_master_table function to support tibble input. Please le me know if you have any further questions.
